/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const MyReservationsLazyImport = createFileRoute('/my-reservations')()
const ManageCompaniesLazyImport = createFileRoute('/manage-companies')()
const LoginLazyImport = createFileRoute('/login')()
const CreateNewCompanyLazyImport = createFileRoute('/create-new-company')()
const CompanyReservationsLazyImport = createFileRoute('/company-reservations')()
const CompanyApprovalLazyImport = createFileRoute('/company-approval')()
const IndexLazyImport = createFileRoute('/')()
const ProviderCompanyIdLazyImport = createFileRoute('/provider/$companyId')()
const CompanyDetailsCompanyIdLazyImport = createFileRoute(
  '/company-details/$companyId',
)()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const MyReservationsLazyRoute = MyReservationsLazyImport.update({
  id: '/my-reservations',
  path: '/my-reservations',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/my-reservations.lazy').then((d) => d.Route),
)

const ManageCompaniesLazyRoute = ManageCompaniesLazyImport.update({
  id: '/manage-companies',
  path: '/manage-companies',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manage-companies.lazy').then((d) => d.Route),
)

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const CreateNewCompanyLazyRoute = CreateNewCompanyLazyImport.update({
  id: '/create-new-company',
  path: '/create-new-company',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create-new-company.lazy').then((d) => d.Route),
)

const CompanyReservationsLazyRoute = CompanyReservationsLazyImport.update({
  id: '/company-reservations',
  path: '/company-reservations',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/company-reservations.lazy').then((d) => d.Route),
)

const CompanyApprovalLazyRoute = CompanyApprovalLazyImport.update({
  id: '/company-approval',
  path: '/company-approval',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/company-approval.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProviderCompanyIdLazyRoute = ProviderCompanyIdLazyImport.update({
  id: '/provider/$companyId',
  path: '/provider/$companyId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/provider/$companyId.lazy').then((d) => d.Route),
)

const CompanyDetailsCompanyIdLazyRoute =
  CompanyDetailsCompanyIdLazyImport.update({
    id: '/company-details/$companyId',
    path: '/company-details/$companyId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/company-details/$companyId.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/company-approval': {
      id: '/company-approval'
      path: '/company-approval'
      fullPath: '/company-approval'
      preLoaderRoute: typeof CompanyApprovalLazyImport
      parentRoute: typeof rootRoute
    }
    '/company-reservations': {
      id: '/company-reservations'
      path: '/company-reservations'
      fullPath: '/company-reservations'
      preLoaderRoute: typeof CompanyReservationsLazyImport
      parentRoute: typeof rootRoute
    }
    '/create-new-company': {
      id: '/create-new-company'
      path: '/create-new-company'
      fullPath: '/create-new-company'
      preLoaderRoute: typeof CreateNewCompanyLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/manage-companies': {
      id: '/manage-companies'
      path: '/manage-companies'
      fullPath: '/manage-companies'
      preLoaderRoute: typeof ManageCompaniesLazyImport
      parentRoute: typeof rootRoute
    }
    '/my-reservations': {
      id: '/my-reservations'
      path: '/my-reservations'
      fullPath: '/my-reservations'
      preLoaderRoute: typeof MyReservationsLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/company-details/$companyId': {
      id: '/company-details/$companyId'
      path: '/company-details/$companyId'
      fullPath: '/company-details/$companyId'
      preLoaderRoute: typeof CompanyDetailsCompanyIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/provider/$companyId': {
      id: '/provider/$companyId'
      path: '/provider/$companyId'
      fullPath: '/provider/$companyId'
      preLoaderRoute: typeof ProviderCompanyIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/company-approval': typeof CompanyApprovalLazyRoute
  '/company-reservations': typeof CompanyReservationsLazyRoute
  '/create-new-company': typeof CreateNewCompanyLazyRoute
  '/login': typeof LoginLazyRoute
  '/manage-companies': typeof ManageCompaniesLazyRoute
  '/my-reservations': typeof MyReservationsLazyRoute
  '/register': typeof RegisterLazyRoute
  '/company-details/$companyId': typeof CompanyDetailsCompanyIdLazyRoute
  '/provider/$companyId': typeof ProviderCompanyIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/company-approval': typeof CompanyApprovalLazyRoute
  '/company-reservations': typeof CompanyReservationsLazyRoute
  '/create-new-company': typeof CreateNewCompanyLazyRoute
  '/login': typeof LoginLazyRoute
  '/manage-companies': typeof ManageCompaniesLazyRoute
  '/my-reservations': typeof MyReservationsLazyRoute
  '/register': typeof RegisterLazyRoute
  '/company-details/$companyId': typeof CompanyDetailsCompanyIdLazyRoute
  '/provider/$companyId': typeof ProviderCompanyIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/company-approval': typeof CompanyApprovalLazyRoute
  '/company-reservations': typeof CompanyReservationsLazyRoute
  '/create-new-company': typeof CreateNewCompanyLazyRoute
  '/login': typeof LoginLazyRoute
  '/manage-companies': typeof ManageCompaniesLazyRoute
  '/my-reservations': typeof MyReservationsLazyRoute
  '/register': typeof RegisterLazyRoute
  '/company-details/$companyId': typeof CompanyDetailsCompanyIdLazyRoute
  '/provider/$companyId': typeof ProviderCompanyIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company-approval'
    | '/company-reservations'
    | '/create-new-company'
    | '/login'
    | '/manage-companies'
    | '/my-reservations'
    | '/register'
    | '/company-details/$companyId'
    | '/provider/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company-approval'
    | '/company-reservations'
    | '/create-new-company'
    | '/login'
    | '/manage-companies'
    | '/my-reservations'
    | '/register'
    | '/company-details/$companyId'
    | '/provider/$companyId'
  id:
    | '__root__'
    | '/'
    | '/company-approval'
    | '/company-reservations'
    | '/create-new-company'
    | '/login'
    | '/manage-companies'
    | '/my-reservations'
    | '/register'
    | '/company-details/$companyId'
    | '/provider/$companyId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CompanyApprovalLazyRoute: typeof CompanyApprovalLazyRoute
  CompanyReservationsLazyRoute: typeof CompanyReservationsLazyRoute
  CreateNewCompanyLazyRoute: typeof CreateNewCompanyLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ManageCompaniesLazyRoute: typeof ManageCompaniesLazyRoute
  MyReservationsLazyRoute: typeof MyReservationsLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  CompanyDetailsCompanyIdLazyRoute: typeof CompanyDetailsCompanyIdLazyRoute
  ProviderCompanyIdLazyRoute: typeof ProviderCompanyIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CompanyApprovalLazyRoute: CompanyApprovalLazyRoute,
  CompanyReservationsLazyRoute: CompanyReservationsLazyRoute,
  CreateNewCompanyLazyRoute: CreateNewCompanyLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ManageCompaniesLazyRoute: ManageCompaniesLazyRoute,
  MyReservationsLazyRoute: MyReservationsLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  CompanyDetailsCompanyIdLazyRoute: CompanyDetailsCompanyIdLazyRoute,
  ProviderCompanyIdLazyRoute: ProviderCompanyIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/company-approval",
        "/company-reservations",
        "/create-new-company",
        "/login",
        "/manage-companies",
        "/my-reservations",
        "/register",
        "/company-details/$companyId",
        "/provider/$companyId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/company-approval": {
      "filePath": "company-approval.lazy.tsx"
    },
    "/company-reservations": {
      "filePath": "company-reservations.lazy.tsx"
    },
    "/create-new-company": {
      "filePath": "create-new-company.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/manage-companies": {
      "filePath": "manage-companies.lazy.tsx"
    },
    "/my-reservations": {
      "filePath": "my-reservations.lazy.tsx"
    },
    "/register": {
      "filePath": "register.lazy.tsx"
    },
    "/company-details/$companyId": {
      "filePath": "company-details/$companyId.lazy.tsx"
    },
    "/provider/$companyId": {
      "filePath": "provider/$companyId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
